name: Python-package
 
on: 
    push:
        branches: 
            - main
            - develop
jobs:
  my_test: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: execute script
          run: |
            touch tmp
            ls
            python Tests.py > tmp.txt
            python Tests.py
            ls
        - name: copy
          run:
            touch tmp
            python Tests.py > tmp.txt
            curl -X POST -H "Content-Type: application/json" -d "{"chat_id": "123456789", "text": "This is a test from curl", "disable_notification": true}"https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage
