name: Python-package
 
on: 
    push:
        branches: 
            - main
            - develop
jobs:
  my_test: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: execute script
          run: |
            touch tmp
            ls
            export TESTS_RESULT = $(python Tests.py)
            python Tests.py > tmp
        - name: copy
          if: always()
          run: |
            sudo apt update -y 
            sudo apt install httpie -y
            http POST https://api.telegram.org/bot5548883363:AAGz7FuLJBJ4c9b_3TIiWmFaT_PvoIS43_8/sendMessage chat_id=869012749 text=echo $(python Tests.py) --ignore-stdin
 
