name: Python-package

on: 
    push:
        branches: 
            - main
            - develop
jobs:
  my_test: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: execute script
          run: |
            python Tests.py
        - name: send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              ${{ github.actor }} created commit:
              Commit message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
